### ISSUE TITLE
Format the README as markdown and not ipynb file

### ISSUE THREAD

**Issue by Naereen** [agahkarakuzu/joctave#2]
Hi,
Right now, it's almost impossible to understand what this project does, when landing on the main page and its non-formatted `README.ipynb` file…
Could you try to format the README as markdown and not ipynb file?
Thanks

**Comment by Naereen** [comment]
You can probably convert your notebook directly with:
```bash
$ jupyter-nbconvert README.ipynb --to markdown
```

**Comment by agahkarakuzu** [comment]
@Naereen thank you for the suggestions:) Taken as a github repo, I agree that this one is not self explanatory. I was using this as a playground to discover Binder. I can actually remove this one.  

> You can probably convert your notebook directly with nbconvert

Converting notebooks to static markdowns can be useful for educational/blog purposes, but not enough for reporting scientific output, where you may want users to interact with your code on the fly, tweak few parameters and see how they affect the output. [Binder](https://mybinder.org/) is one of my fav ways to do it.

I have few examples here: 

https://agahkarakuzu.github.io/

**Comment by Naereen** [comment]
I know what notebook are… I was talking about this `README.ipynb` file.

**Comment by agahkarakuzu** [comment]
You have an interesting take on what I've explained above (which was definitely not a mere explanation of what a notebook is, but the role of Binder in making them online executable).  

I can comprehend that you are talking about `README.ipynb` :) You are right, the sensible format for a file sitting with the README name on a github repo is .md. The exact motivation behind keeping this README file as .ipynb instead of a .md had to do with binderizing them. 

If you are interested, the context of this repo is now available here:

 [![Binder](https://mybinder.org/badge.svg)](https://mybinder.org/v2/gh/agahkarakuzu/dogSCspmrt/master?filepath=dogSCspmrt.ipynb)

Thank you for sharing your concerns. I will be more careful to provide a more descriptive front page for people reaching via GitHub.
